title: 'Graphic Design, Art, Photography & Technology '
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.2141653
  brandStrength: 0
  lightness: 0.8254638
  brandColors:
    - '#E8C665'
    - '#4C2E21'
    - '#A44217'
    - '#E17F26'
    - '#FCE7D0'
  rhythmicContrast: 0.8600338
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Expressão
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.3844857
layout_spectrum: 0.188027
