name: Expressão
favicon: null
layout_spectrum: 0.88794
typography_spectrum: 0.62188
title: 'Graphic Design, Art, Photography & Technology '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#c7c9ca'
    - '#000000'
    - '#808080'
    - '#555555'
  brandStrength: 0.375
  lightness: 0.8125
  saturation: 0.4375
  rhythmicContrast: 0.75
purpose: []
