name: Expressão
favicon: null
layout_spectrum: 0.30088224564678967
typography_spectrum: 0.9064607329200953
title: 'Graphic Design, Art, Photography & Technology '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.34677351103164256
  lightness: 0.5348380394279957
  saturation: 0.18515606550499797
  rhythmicContrast: 0.4042921089567244
purpose: []
