name: Expressão
favicon: null
layout_spectrum: 0.59002
typography_spectrum: 0.33673
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c9d9f0'
    - '#0a0605'
    - '#ffffff'
    - '#867a6e'
    - '#db9b78'
  brandStrength: 0.25
  lightness: 0.3125
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
