name: Expressão
favicon: null
layout_spectrum: 0.188027
typography_spectrum: 0.3844857
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E8C665'
    - '#4C2E21'
    - '#A44217'
    - '#E17F26'
    - '#FCE7D0'
  brandStrength: 0
  lightness: 0.8254638
  saturation: 0.2141653
  rhythmicContrast: 0.8600338
purpose: []
